[sqllog]
path = "test_logs/"

[error]
file = "work/errors.log"

[logging]
file = "work/app.log"
level = "warn"
retention_days = 1

[filter]
enable = true

[filter.sql]
includes = ["DROP"]

[exporter.csv]
file = "work/output_sql_filter.csv"
overwrite = true
