[sqllog]
path = "test_logs/"

[error]
file = "work/errors.log"

[logging]
file = "work/app.log"
level = "warn"
retention_days = 1

[filter]
enable = true

[filter.include]
users = ["TESTUSER"]

[filter.indicators]
min_runtime_ms = 50

[filter.sql]
includes = ["SELECT"]

[exporter.csv]
file = "work/output_all_filters.csv"
overwrite = true
