[sqllog]
path = "test_logs/"

[error]
file = "work/errors.log"

[logging]
file = "work/app.log"
level = "warn"
retention_days = 1

[filter]
enable = true

[filter.indicators]
min_runtime_ms = 50

[exporter.csv]
file = "work/output_indicators.csv"
overwrite = true
